### ISSUE TITLE
bank transfer GoPay callback issue

### ISSUE THREAD

**Issue by mattusik** [remp2020/crm-gopay-module#11]
Hello, 
I run into issue while processing GoPay callback for bank transfer.  

Stack trace: 
```
Error: Call to undefined method Crm\PaymentsModule\Gateways\BankTransfer::notification()
#7 /var/app/current/vendor/remp/crm-gopay-module/src/api/GoPayNotificationHandler.php(76): Crm\GoPayModule\Api\GoPayNotificationHandler::handle
#6 /var/app/current/vendor/remp/crm-api-module/src/presenters/ApiPresenter.php(124): Crm\ApiModule\Presenters\ApiPresenter::renderApi
#5 [internal](0): ReflectionMethod::invokeArgs
#4 /var/app/current/vendor/nette/application/src/Application/UI/Component.php(92): Nette\Application\UI\Component::tryCall
#3 /var/app/current/vendor/nette/application/src/Application/UI/Presenter.php(214): Nette\Application\UI\Presenter::run
#2 /var/app/current/vendor/nette/application/src/Application/Application.php(149): Nette\Application\Application::processRequest
#1 /var/app/current/vendor/nette/application/src/Application/Application.php(83): Nette\Application\Application::run
#0 /index.php(13): null
```

Can you guys help me with this? ☺️

**Comment by rootpd** [comment]
Hi, this looks like the payment (record in the database) wasn't created correctly. I'm not sure what the process on your side is, but it looks like that the payment that's being processed has `bank_transfer` payment gateway, not `gopay`. In DB it's `payments.payment_gateway_id` column.

This doesn't sound standard, because if you were redirected to the Gopay correctly, the payment must have had `gopay` payment gateway configured.

Questions:

1. How much of the implementation of payment process is your own?  
1. Is there something, that could have changed the gateway in the database?  
1. What version do the CRM modules have? You should probably be on `0.32` or freshly released `0.33`.
